name: resilio sync for hassos
version: 1.1.1
slug: resilio_sync_for_hassos
description: 使用resilio sync同步/backup目录到其它设备。安装完成后请通过IP:8888访问
arch:
  - armhf
  - aarch64  
  - amd64  
ports:
  8888/tcp: 8888
  55555/tcp: 55555
ports_description:
  8888/tcp: webUI
  55555/tcp: listening_port
map:
  - backup:rw
  - config:rw